-- Cost Cop demo cleanup (drops objects created by setup.sql).
USE ROLE ACCOUNTADMIN;
DROP USER IF EXISTS COST_COP_BOT_SVC_USER;

SET current_user = (SELECT CURRENT_USER());

REVOKE ROLE COST_COP_BOT_ROLE FROM USER IDENTIFIER($current_user);

DROP ROLE IF EXISTS COST_COP_BOT_ROLE;

DROP WAREHOUSE IF EXISTS COST_COP_DEMO_WH_A;
DROP WAREHOUSE IF EXISTS COST_COP_DEMO_WH_B;
DROP WAREHOUSE IF EXISTS COST_COP_DEMO_WH_C;

-- Ensure cleanup successful
SHOW WAREHOUSES LIKE 'COST_COP_DEMO_WH_%';
SHOW USERS LIKE 'COST_COP_%';
SHOW ROLES LIKE 'COST_COP_%';
